export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const ADD_TO_FAVORITE_AND_UPDATE = 'ADD_TO_FAVORITE_AND_UPDATE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const REMOVE_FAVORITE_AND_UPDATE = 'REMOVE_FAVORITE_AND_UPDATE';
export const UPDATE_FAVORITES = 'UPDATE_FAVORITES';
export const UPDATE_FAVORITES_ASYNC = 'UPDATE_FAVORITES_ASYNC';

export const FETCH_ARTIST_INFO = 'FETCH_ARTIST_INFO';
export const FETCH_ARTIST_INFO_START = 'FETCH_ARTIST_INFO_START';
export const FETCH_ARTIST_INFO_SUCCESS = 'FETCH_ARTIST_INFO_SUCCESS';
export const FETCH_ARTIST_INFO_FAIL = 'FETCH_ARTIST_INFO_FAIL';

export const FETCH_ARTIST_ALBUMS = 'FETCH_ARTIST_ALBUMS';
export const FETCH_ARTIST_ALBUMS_START = 'FETCH_ARTIST_ALBUMS_START';
export const FETCH_ARTIST_ALBUMS_SUCCESS = 'FETCH_ARTIST_ALBUMS_SUCCESS';
export const FETCH_ARTIST_ALBUMS_FAIL = 'FETCH_ARTIST_ALBUMS_FAIL';