export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const ADD_TO_FAVORITE_AND_UPDATE = 'ADD_TO_FAVORITE_AND_UPDATE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const REMOVE_FAVORITE_AND_UPDATE = 'REMOVE_FAVORITE_AND_UPDATE';
export const UPDATE_FAVORITES = 'UPDATE_FAVORITES';
export const UPDATE_FAVORITES_ASYNC = 'UPDATE_FAVORITES_ASYNC';